create a simple neural network from scratch

In [2]:
inputs= [1.2,5.3,2.4]
print(inputs) 

[1.2, 5.3, 2.4]


In [3]:
weights=[3.1,2.1,8.7]
print(weights)

[3.1, 2.1, 8.7]


In [4]:
bias =3
print(bias)

3


In [5]:
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

38.730000000000004


Simple Layer of Neurons  

In [6]:
inputs= [1.0,2.0,3.0,2.4]

In [7]:
weights1=[0.2,0.8,-0.5,1.0]  # weight of first neuron 
weights2=[0.5,-0.91,0.25,-0.5]# second 
weights3=[-0.25,-0.28,0.15,0.87]# third 

bias1 = 2
bias2 = 3
bias3 = 0.5

In [8]:
output=inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1

output2=inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2

output3=inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3

print(output)
print(output2)
print(output3)

4.7
1.23
2.2279999999999998


Dot Product to code neural network 

In [9]:
import numpy as np 


In [10]:
weights=np.array([[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.25,-0.5],[-0.25,-0.28,0.15,0.87]])
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.25, -0.5 ],
       [-0.25, -0.28,  0.15,  0.87]])

In [11]:
biases=[2,3,0.5]

In [12]:
output = np.dot(weights,inputs)+biases
output 

array([4.7  , 1.23 , 2.228])

Layer of neurons 

In [13]:
import numpy as np

In [14]:
X=[
    [1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]
X

[[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

In [28]:
class DeneseLayer:
    def __init__(self,n_inputs,n_neuron):
        self.weights=0.12*np.random.randn(n_inputs,n_neuron)
        self.biases=np.zeros((1,n_neuron))
        
    def forward_prob(self,inputs):
        self.output=np.dot(inputs,self.weights)+self.biases
        


In [29]:
layer_1=DeneseLayer(4,5)
layer_1

In [31]:
layer_1.forward_prob(X)


[[ 0.15496851  0.76893687  0.55799092 -1.09401202 -0.43007899]
 [-0.09684496  1.99774982  1.634516    0.34809547  0.04362136]
 [ 0.7525193  -0.515483    0.78820217 -1.46669148 -0.40633314]]


In [32]:
print(layer_1.output)

[[ 0.15496851  0.76893687  0.55799092 -1.09401202 -0.43007899]
 [-0.09684496  1.99774982  1.634516    0.34809547  0.04362136]
 [ 0.7525193  -0.515483    0.78820217 -1.46669148 -0.40633314]]


In [ ]:
layer_2=DeneseLayer(5,2)

In [ ]:
layer_2.forward_prob(layer_1.output)

In [ ]:
print(layer_2.output)